services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    networks:
      - frontend_network
      - project_network
    depends_on:
      - keycloak
    restart: unless-stopped
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"
    networks:
      - backend_network
      - project_network
  cache:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: cache
    volumes:
      - nginx_cache:/var/cache/nginx
    ports:
      - "80:80"
    networks:
      - project_network
  postgres:
    image: postgres:16
    container_name: postgres
    env_file:
      - ./postgres/.env
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - project_network
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    container_name: keycloak
    env_file:
      - ./keycloak/.env
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - frontend_network
      - project_network
    command:
      - start-dev
volumes:
  nginx_cache:
  pg_data:
networks:
  project_network:
    name: project_network
  frontend_network:
    name: frontend_network
  backend_network:
    name: backend_network
