services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    networks:
      - frontend_network
      - project_network
    depends_on:
      - keycloak
    restart: unless-stopped
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"
    networks:
      - backend_network
      - project_network
  explore-service:
    build:
      context: ./backend/explore-service
      dockerfile: Dockerfile
    container_name: explore-service
    env_file:
      - ./backend/.env
    ports:
      - "5001:5000"
    networks:
      - backend_network
  interaction-service:
    build:
      context: ./backend/interaction-service
      dockerfile: Dockerfile
    container_name: interaction-service
    env_file:
      - ./backend/.env
    ports:
      - "5002:5000"
    networks:
      - backend_network
  notifications-service:
    build:
      context: ./backend/notifications-service
      dockerfile: Dockerfile
    container_name: notifications-service
    env_file:
      - ./backend/.env
    ports:
      - "5003:5000"
    networks:
      - backend_network
  post-service:
    build:
      context: ./backend/post-service
      dockerfile: Dockerfile
    container_name: post-service
    env_file:
      - ./backend/.env
    ports:
      - "5004:5000"
    networks:
      - backend_network
  search-history-service:
    build:
      context: ./backend/search-history-service
      dockerfile: Dockerfile
    container_name: search-history-service
    env_file:
      - ./backend/.env
    ports:
      - "5005:5000"
    networks:
      - backend_network
  tags-service:
    build:
      context: ./backend/tags-service
      dockerfile: Dockerfile
    container_name: tags-service
    env_file:
      - ./backend/.env
    ports:
      - "5006:5000"
    networks:
      - backend_network
  users-service:
    build:
      context: ./backend/users-service
      dockerfile: Dockerfile
    container_name: users-service
    env_file:
      - ./backend/.env
    ports:
      - "5007:5000"
    networks:
      - backend_network
  cache:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: cache
    volumes:
      - nginx_cache:/var/cache/nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      - project_network
  postgres:
    image: postgres:16
    container_name: postgres
    env_file:
      - ./postgres/.env
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - project_network
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    container_name: keycloak
    env_file:
      - ./keycloak/.env
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - frontend_network
      - project_network
    command:
      - start-dev

volumes:
  nginx_cache:
  pg_data:
networks:
  project_network:
    name: project_network
  frontend_network:
    name: frontend_network
  backend_network:
    name: backend_network
