x-backend-service: &backend_service
  image: backend-microservices
  env_file:
    - ./backend/.env
  networks:
    - backend_network
  depends_on:
    keycloak:
      condition: service_healthy
    cache:
      condition: service_healthy
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    networks:
      - frontend_network
      - project_network
    volumes:
      - ./frontend:/app
    depends_on:
      - keycloak
    restart: unless-stopped

  explore-service:
    <<: *backend_service
    command: ["./explore-services"]
    container_name: explore-service
    ports:
      - "5001:5000"

  interaction-service:
    <<: *backend_service
    command: ["./interaction-services"]
    container_name: interaction-service
    ports:
      - "5002:5000"

  notifications-service:
    <<: *backend_service
    command: ["./notifications-services"]
    container_name: notifications-service
    ports:
      - "5003:5000"
  post-service:
    <<: *backend_service
    command: ["./post-services"]
    container_name: post-service
    ports:
      - "5004:5000"
  search-history-service:
    <<: *backend_service
    command: ["./search-history-services"]
    container_name: search-history-service
    ports:
      - "5005:5000"
  tags-service:
    <<: *backend_service
    command: ["./tags-services"]
    container_name: tags-service
    ports:
      - "5006:5000"
  users-service:
    <<: *backend_service
    command: ["./users-services"]
    container_name: users-service
    ports:
      - "5007:5000"
  cache:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: cache
    volumes:
      - nginx_cache:/var/cache/nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      - backend_network
      - project_network

  postgres:
    image: postgres:16
    container_name: postgres
    env_file:
      - ./postgres/.env
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - project_network
    healthcheck:
      test: ["CMD", "curl", "-fk", "https://localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    container_name: keycloak
    env_file:
      - ./keycloak/.env
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - frontend_network
      - project_network
      - backend_network
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:8080/realms/my-realm/.well-known/openid-configuration",
        ]
      interval: 5s
      timeout: 5s
      retries: 10
    command:
      - start-dev
volumes:
  nginx_cache:
  pg_data:
networks:
  project_network:
    name: project_network
  frontend_network:
    name: frontend_network
  backend_network:
    name: backend_network
