x-backend-service: &backend_service
  image: backend-microservices
  env_file:
    - ./backend/.env
  networks:
    - backend_network
  depends_on:
    - keycloak
    - postgres

services:
  postgres:
    image: postgres:16
    container_name: postgres
    env_file:
      - ./postgres/.env
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - project_network

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    container_name: keycloak
    env_file:
      - ./keycloak/.env
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - project_network
      - backend_network
    command: >
      start-dev --proxy-headers=xforwarded --hostname-strict=false --hostname-strict-https=false --hostname-admin-url=https://localhost/auth
    volumes:
      - ./keycloak/data/import:/opt/keycloak/data/import
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/realms/master"]
      interval: 5s
      timeout: 3s
      retries: 10

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    networks:
      - project_network
    volumes:
      - ./frontend:/app
    restart: unless-stopped
  cache:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: cache
    volumes:
      - nginx_cache:/var/cache/nginx
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "443:443"
    networks:
      - backend_network
      - project_network
    depends_on:
      - explore-service
      - interaction-service
      - notifications-service
      - post-service
      - search-history-service
      - tags-service
      - users-service
      - keycloak

    restart: on-failure

  explore-service:
    <<: *backend_service
    command: ["./explore-services"]
    container_name: explore-service
    ports:
      - "5001:5000"

  interaction-service:
    <<: *backend_service
    command: ["./interaction-services"]
    container_name: interaction-service
    ports:
      - "5002:5000"

  notifications-service:
    <<: *backend_service
    command: ["./notifications-services"]
    container_name: notifications-service
    ports:
      - "5003:5000"
  post-service:
    <<: *backend_service
    command: ["./post-services"]
    container_name: post-service
    ports:
      - "5004:5000"
  search-history-service:
    <<: *backend_service
    command: ["./search-history-services"]
    container_name: search-history-service
    ports:
      - "5005:5000"
  tags-service:
    <<: *backend_service
    command: ["./tags-services"]
    container_name: tags-service
    ports:
      - "5006:5000"
  users-service:
    <<: *backend_service
    command: ["./users-services"]
    container_name: users-service
    ports:
      - "5007:5000"

volumes:
  nginx_cache:
  pg_data:

networks:
  project_network:
    name: project_network
  backend_network:
    name: backend_network
