apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configuration
  namespace: ingress-nginx
data:
  use-proxy-protocol: "false"
  proxy-connect-timeout: "10"
  proxy-read-timeout: "60"
  proxy-send-timeout: "60"
  client-max-body-size: "10m"
  enable-real-ip: "true"
  use-forwarded-headers: "true"
  ssl-redirect: "true"
  server-tokens: "false"
  log-format-escape-json: "true"
