"use client";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import HomePageFunctions from "@/app/home/home";
import WhoToFollow from "./components/whoToFollow";
import Trending from "./components/trending";
import { usePathname } from "next/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();
  const showHome = !["/", "/login", "/signup"].includes(pathname);
  const showWhoToFollow = ![
    "/",
    "/login",
    "/signup",
    "/messages",
    "/settings",
  ].includes(pathname);
  const showTrending = ![
    "/",
    "/login",
    "/signup",
    "/explore",
    "/messages",
    "/settings",
  ].includes(pathname);
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <section>{showHome && <HomePageFunctions.Home />}</section>
        <aside>
          {showWhoToFollow && <WhoToFollow />}
          {showTrending && <Trending />}
        </aside>
        <main>{children}</main>
      </body>
    </html>
  );
}
