apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: postgres-secret
type: Opaque
data:
  POSTGRES_DB: cG9zdGdyZXM=
  POSTGRES_PASSWORD: aGFzbG8=
  POSTGRES_PORT: NTQzMg==
  POSTGRES_USER: a2V5Y2xvYWs=
