apiVersion: apps/v1
kind: Deployment
metadata:
  name: interaction-service
  labels:
    app: interaction-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: interaction-service
  template:
    metadata:
      labels:
        app: interaction-service
    spec:
      containers:
        - name: interaction-service
          image: adriandob2604/backend-microservices:latest
          command: ["./interaction-services"]
          ports:
            - containerPort: 5000
          env:
            - name: USERNAME
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: USERNAME
            - name: SUPABASE_URL
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: SUPABASE_URL
            - name: SUPABASE_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: SUPABASE_KEY
            - name: KEYCLOAK_JWKS_URL
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: KEYCLOAK_JWKS_URL
